---
title: "Summary statistics"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse) # to manipulate the datasets
library(dplyr)
library(lubridate) # to deal with dates
library(nlme) # to conduct linear mixed effect models
library(car) # to calculate Type III sums of squares
library(lme4) # to conduct generalized mixed effect models
library(vegan)
library(ggplot2)
library(Rmisc)
library(multcomp)
library(mvnormtest)
library(tidyr)
library(rmcorr)
library(glmmTMB)
library(emmeans)

setwd("~/Desktop/Paper_3/Datasets")

sp<-read.csv("SpeciesInfo.csv", header = TRUE)  
transect_meta<-read.csv("Transect_Meta.csv", header = TRUE) %>%
  dplyr::select(Tyear, Status, Year)

visits<-read.csv("Visitations.csv", header = TRUE) %>%
  mutate(Veg = ifelse(as.character(Veg)=="BRANIG"|as.character(Veg)=="HIRINC", 'MUSTARD', 
                      as.character(Veg))) %>%
  mutate(Veg = ifelse(as.character(Veg)=="CRY", "CRYMUR", as.character(Veg))) %>%
  mutate(fine_pollinator = paste(Type_pollinator, Bee_type, sep = "_")) %>%
 # dplyr::filter(fine_pollinator != "NA_") %>%
  mutate(fine_pollinator = dplyr::recode(fine_pollinator, "DIP_" = "DIP", "LID_" = "LID",
                                  "HUM_" = "HUM", "SYP_" = "SYP", "FLY_" = "FLY",
                                  "SAW_" = "SAW")) %>%
  mutate(fine_pollinator_size = paste(fine_pollinator, Size, sep = "_")) %>%
  mutate(fine_pollinator_size = dplyr::recode(fine_pollinator_size, "DIP_NA" = "DIP",
                                              "LID_NA" = "LID", "HUM_NA" = "HUM",
                                              "SYP_NA" = "SYP", "FLY_NA" = "FLY",
                                              "SAW_NA" = "SAW", "BEE_Apis_NA" = "BEE_Apis","BEE_Bombus_NA" = "BEE_Bombus", "BEE_Native_15" = "BEE_Native_10")) %>%
  mutate(Tyear = paste(Transect, Year, Round, sep = "_"))%>%
  mutate_at(vars(Num), ~replace_na(., 0))

og_visits <- read.csv("Visitations.csv", header = TRUE) %>%
  mutate(Tyear = paste(Transect, Year, Round, sep = "_"))

f_transect_abundance<-read.csv("FAbundance_wide.csv", header = TRUE)
quad_flower <- read.csv("quad_flower.csv", header = TRUE)
pollen <- read.csv("pollen22.csv", header = TRUE) %>%
  mutate(Tyear = paste(Transect, "2022", Round, sep = "_" ))

transect_meta_wtransect <- read.csv("Transect_Meta.csv", header = TRUE) %>%
  dplyr::select(Tyear, Transect, Status, Year)

unique_obs <- visits%>%
  dplyr::select(Tyear, Transect, Quad, Year, Round, Start) %>%
  filter(Quad != "walk") %>%
  filter(!Quad %in% c(2,6,46,38)) %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  distinct(., Tyear_quad, Start, .keep_all = TRUE)

```



```{r, echo=FALSE}

##total number of visit occurrences

observation_count <- visits %>%
  filter(Quad != 'walk') %>%
  mutate(TYQR_Start = paste(Transect, Year, Quad, Round, Start, sep = "_")) #%>%
#  filter(Year == 2022)
 # filter(Year == 2021)

walk_count <- visits %>%
  filter(Quad == 'walk') %>%
  mutate(TYQR_Start = paste(Transect, Year, Quad, Round, Start, sep = "_")) %>%
  filter(Year == 2022)
 # filter(Year == 2021)

##503 observations -> 168 observation hours
#######248 obs from 2021, 255 from 2022
##47 walks -> 8 walk hours
#######15 walks from 2021, 32 from 2022

#128 visits (132 if all visited, but missed two in first round and two of the same in later in 2021), averaging 4 20 minute observations per visit

pol_group_obs <- visits %>%
  #filter(fine_pollinator_size != "BEE_Apis") %>%
  filter(Year == 2021) %>%
  #filter(Year == 2021) %>%
  group_by(fine_pollinator_size) %>%
  tally() %>%
  filter(fine_pollinator_size!="NA__NA")

pol_group_obs_ggplot <- ggplot(data = pol_group_obs, aes(x=fine_pollinator_size, y=n)) +
  geom_bar(stat = "identity") +
  ylim(0,1000) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))

pol_group_obs_ggplot

#summary of total number of visits to less fine groups

pol_group_visits <- visits %>%
  mutate(fine_pollinator = paste(Type_pollinator, Bee_type)) %>%
  filter(!is.na(Num)) %>%
  dplyr::group_by(fine_pollinator) %>%
  dplyr::summarise(Num = sum(Num)) 

##visits per group per burn status
visits_meta <- merge(visits, transect_meta, by = "Tyear")

pol_group_obs_burn <- visits_meta %>%
  group_by(fine_pollinator_size, Status, Year.x) %>%
  tally() %>%
  filter(fine_pollinator_size != "NA__NA") 

pol_group_obs_burn_ggplot <- ggplot(data = pol_group_obs_burn, aes(x=fine_pollinator_size, y=n)) +
  geom_bar(stat = "identity") +
  ylim(0,600) +
  facet_wrap(~Year.x + Status) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))

pol_group_obs_burn <- pol_group_obs_burn %>%
  filter(fine_pollinator_size != "BEE_Apis")

pol_group_obs_burn_ggplot_noapis <- ggplot(data = pol_group_obs_burn, aes(x=fine_pollinator_size, y=n)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year.x + Status) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))

pol_group_obs_burn_ggplot
pol_group_obs_burn_ggplot_noapis
```

```{r}

Transects <- data.frame(Transects = c(unique(visits$Transect)))
Years <- data.frame(Year = c("2021", "2022"))
Rounds <- data.frame(Rounds = c("1", "2", "3"))

Transect_temp <- crossing(Transects, Years, Rounds) ##wow that's very useful

##calculating the number of flowers per quad
quad_flower_sum <- quad_flower %>%
  dplyr::select(., -c(Total, Average)) %>%
  group_by(Tyear) %>%
  dplyr::summarise(across(X0:SPECIAL, sum)) %>%
  mutate_all(~replace(., is.na(.),0)) 

##convert to long format

quad_flower_sum <- quad_flower_sum %>%
  tidyr::gather(., key = "Quad", value = "flower", X0, X5, X10, X15, X20, X25, X30,
                X35, X40, X45, SPECIAL) 

quad_flower_sum$Quad <- gsub("X", "", as.character(quad_flower_sum$Quad))
quad_flower_sum$Quad <- as.integer(quad_flower_sum$Quad)

quad_flower_sum$Quad <- replace(quad_flower_sum$Quad, is.na(quad_flower_sum$Quad), 'special')

##Visitation rate calculations


quad_visit_sum <- visits %>% ##total visits per quad per observation
  mutate(Tyear = paste(Transect, Year, Round, sep = "_")) %>%
  group_by(Tyear, Start, Quad, Temp) %>%
  dplyr::summarise(visits = sum(Num)) %>%
  filter(Quad != 'walk') %>%
  mutate(Quad= ifelse( Quad =="Special", "special", Quad)) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  filter(Quad != 2) %>%
  filter(Quad!= 6) 

##Merge flower abundance and total touches

quad_flower_visit <- left_join(quad_visit_sum, quad_flower_sum, by = c("Tyear", "Quad")) %>%
  filter(!is.na(flower)) %>%
  mutate(visit_flower_hour = (visits/flower)*3) %>%
  filter(Quad != 'special') %>%  
  mutate(visit_flower_hour = ifelse(is.na(visit_flower_hour), 0, visit_flower_hour)) %>%
  filter(visit_flower_hour < Inf) 

##merge information about burn status

quad_flower_visit <- merge(quad_flower_visit, transect_meta, by = "Tyear") 

p <- ggplot(quad_flower_visit, aes(x = Status, y = visit_flower_hour)) +
  geom_boxplot() +
  facet_wrap(~Year)

p

quad_flower_visit2 <- merge(quad_flower_visit, transect_meta_wtransect, by = "Tyear") %>%
  dplyr::select(Tyear, Transect, Status.x, visit_flower_hour,Year.x) %>%
  mutate(Year.x = as.factor(Year.x))

visit_model <- nlme::lme(visit_flower_hour ~ Status.x*Year.x, random = ~1|Transect, data = quad_flower_visit2)
car::Anova(visit_model, type = "III")
summary(visit_model)

quad_flower_visit_avg <- quad_flower_visit %>%
  group_by(Tyear, Status) %>%
  dplyr::summarise(mean_visit_rate = mean(visit_flower_hour), n=n()) %>%
  merge(.,transect_meta, by = "Tyear") 

p2 <- ggplot(quad_flower_visit_avg, aes(x = Status.y, y = mean_visit_rate)) +
  geom_boxplot() +
  facet_wrap(~Year)

p2

quad_flower_visit_avg2 <- merge(quad_flower_visit_avg, transect_meta_wtransect, by = "Tyear") %>%
  dplyr::select(Tyear, Transect, Status, mean_visit_rate,n,Year.x) %>%
  mutate(Year.x = as.factor(Year.x))

visit_model <- lme(mean_visit_rate ~ Status*Year.x, random = ~1|Transect, data = quad_flower_visit_avg2)
Anova(visit_model, type = "III")
summary(visit_model)

```

```{r}

#start with quad_flower_visit

avg.quad.visits <- quad_flower_visit %>%
  group_by(Tyear) %>%
  dplyr::summarise(visits = mean(visits)) %>%
  left_join(., transect_meta_wtransect, by = "Tyear") %>%
  mutate(across('visits'), round, 0) %>%
  mutate(visits = as.integer(visits)) %>%
  left_join(transect_meta_wtransect, ., by = "Tyear") %>%
  mutate(visits = ifelse(is.na(visits), 0 ,visits)) %>%
  mutate(Year.x = as.factor(Year.x))

avg.quad.visits.model <- glmmTMB(visits~ Status.x*Year.x, family = "nbinom1", data = avg.quad.visits) #transect random removed because it was throwing close to 0 variances
summary(avg.quad.visits.model)
Anova(avg.quad.visits.model, type = "III")

avg.quad.visits.plot <- ggplot(avg.quad.visits, aes(x=Status.x, y= visits)) +
  geom_violin() +
  geom_point() +
  facet_wrap(~Year.x)

```
```{r}
#is it because of differences in flower number

quad_flower_visit.wmeta <- quad_flower_visit %>%
  left_join(.,transect_meta_wtransect, by = "Tyear") %>%
  mutate(visits = as.integer(visits)) %>%
  mutate(Year = as.factor(Year))

visits.2.flower.plot <- ggplot(quad_flower_visit.wmeta, aes(x = flower, y = visits)) +
  geom_point() +
  facet_wrap(~Year + Status) +
#  xlim(0,2000) + 
  geom_smooth(method='lm')

quad.flower.visit.model <- glmmTMB(visits~flower*Status*Year, family = "nbinom1", data = quad_flower_visit.wmeta)
summary(quad.flower.visit.model)
Anova(quad.flower.visit.model, type = "III")

avg.quad.visits.model <- glmmTMB(visits~ Status.x*Year.x, family = "nbinom1", data = avg.quad.visits) #transect random removed because it was throwing close to 0 variances
summary(avg.quad.visits.model)
Anova(avg.quad.visits.model, type = "III")  

```


```{r}
#Correlation of activity with time of day

#quad_flower_visit_date <- quad_flower_visit %>%
#  mutate(hmStart = as.numeric(hm(quad_flower_visit$Start))) %>%
#  mutate(Stat_year = paste(Status, Year, sep = "_"))

quad_flower_visit_date <- quad_flower_visit %>%
  mutate(minute = as.numeric(substring(Start,1, nchar(Start)-3))*60 + as.numeric(substring(Start, nchar(Start)-1, nchar(Start)))) %>%
  mutate(Stat_year = paste(Status, Year, sep = "_")) %>%
  mutate(GrpTyear = substring(Tyear, 1, nchar(Tyear)-2))

corr_visit_time_plot <- ggplot(quad_flower_visit_date, aes(x = minute, y = visit_flower_hour, shape=as.factor(Year))) +
  facet_wrap(~Status) +
  geom_point(aes(color=Status)) 

corr_visit_time_plot

#test correlations
#all categories

cor.test(quad_flower_visit_date$minute, quad_flower_visit_date$visit_flower_hour, method = ('pearson'))
anova(lme(visit_flower_hour~minute, random=~1|GrpTyear, data = quad_flower_visit_date))
summary(lme(visit_flower_hour~minute, random=~1|GrpTyear, data = quad_flower_visit_date))

#separate burn status
quad_flower_visit_date.status <- quad_flower_visit_date %>%
#  filter(Status == 'B') 
#  filter(Status == 'M')
  filter(Status == 'U')

cor.test(quad_flower_visit_date.status$minute, quad_flower_visit_date.status$visit_flower_hour, method = ("pearson"))
rmcorr(GrpTyear, minute, visit_flower_hour, quad_flower_visit_date.status)

#using rmcorr for repeated measures
#for all measures
rmcorr(GrpTyear, minute, visit_flower_hour, quad_flower_visit_date)
anova(lme(visit_flower_hour~minute, random=~1|GrpTyear, data = quad_flower_visit_date.status))
summary(lme(visit_flower_hour~minute, random=~1|GrpTyear, data = quad_flower_visit_date.status))


```


```{r}
#Correlation of activity, or number of observations with temperature and windspeed in 2022

quad_flower_visit_temp <- quad_flower_visit %>%
#  dplyr::filter(Year == 2022) %>%
  dplyr::filter(Temp > 0) %>%
  mutate(GrpTyear = substring(Tyear, 1, nchar(Tyear)-2))

quad_flower_visit_temp_plot <- ggplot(quad_flower_visit_temp, aes(x=Temp, y = visit_flower_hour, shape = as.factor(Year))) +
  geom_point(aes(color = Status)) +
  facet_wrap(~Year+Status)

quad_flower_visit_temp_plot

#test correlation of temp and visitation rate

#both years
burnedboth <- quad_flower_visit_temp %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = c("Tyear", "Status", "Year")) %>%
  mutate(Status_year = paste(Status,Year, sep = "_"))

burned.qm <- glmmTMB(visit_flower_hour ~ Temp*Status_year + (1|Transect), family = "nbinom1", data = burnedboth)
summary(burned.qm)
Anova(burned.qm, type = "III")

#burned 2021
burned2021 <- quad_flower_visit_temp %>%
  filter(Year == 2021) %>%
  filter(Status == "B") %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear")

#burned2021.lm <- lme(visit_flower_hour~Temp, random = ~1|Transect, data = burned2021)
#summary(burned2021.lm)

#burned2021.qm <- lme(visit_flower_hour~ Temp + Temp2, random = ~ 1|Transect, data = burned2021)
#summary(burned2021.qm)
#Anova(burned2021.qm, type = "III")

burned2021.gl <- glmmTMB(visit_flower_hour ~ Temp + Temp2 + (1|Transect), family = "nbinom1", data = burned2021)
summary(burned2021.gl)
Anova(burned2021.gl, type = "III")

#burned 2022
burned2022 <- quad_flower_visit_temp %>%
  filter(Year == 2022) %>%
  filter(Status == "B") %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear")

burned2022.gl <- glmmTMB(visit_flower_hour ~ Temp + Temp2, family = "nbinom1", data = burned2022)
summary(burned2022.gl) ##significant
Anova(burned2022.gl, type = "III")

#intermediate 2021
intermediate2021 <- quad_flower_visit_temp %>%
  filter(Year == 2021) %>%
  filter(Status == "M") %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear")

intermediate2021.gl <- glmmTMB(visit_flower_hour ~ Temp + Temp2 + (1|Transect), family = "nbinom1", data = intermediate2021)
summary(intermediate2021.gl)
Anova(intermediate2021.gl, type = "III")

#intermediate 2022
intermediate2022 <- quad_flower_visit_temp %>%
  filter(Year == 2022) %>%
  filter(Status == "M") %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear")

intermediate2022.gl <- glmmTMB(visit_flower_hour ~ Temp + Temp2 + (1|Transect), family = "nbinom1", data = intermediate2022)
summary(intermediate2022.gl)
Anova(intermediate2022.gl, type = "III")

#unburned 2021
unburned2021 <- quad_flower_visit_temp %>%
  filter(Year == 2021) %>%
  filter(Status == "U") %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear")

unburned2021.gl <- glmmTMB(visit_flower_hour ~ Temp + Temp2 + (1|Transect), family = "nbinom1", data = unburned2021)
summary(unburned2021.gl)
Anova(unburned2021.gl, type = "III")

#unburned 2022
unburned2022 <- quad_flower_visit_temp %>%
  filter(Year == 2022) %>%
  filter(Status == "U") %>%
  mutate(Temp2 = Temp^2) %>%
  mutate(visit_flower_hour = as.integer(round(visit_flower_hour, 0))) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear")

unburned2022.gl <- glmmTMB(visit_flower_hour ~ Temp + Temp2 + (1|Transect), family = "nbinom1", data = unburned2022)
summary(unburned2022.gl)
Anova(unburned2022.gl, type = "III")



```


```{r}

##Make a table of all the observations

quad_visit_meta <- quad_visit_sum %>%
  dplyr::rename("total_visits" = "visits")

##Apis visitation rate

quad_visit_sum_apis <- visits %>% ##total visits per quad per observation
  filter(Type_pollinator == "BEE") %>%
  filter(Bee_type == "Apis")%>%
  mutate(Tyear = paste(Transect, Year, Round, sep = "_")) %>%
  group_by(Tyear, Start, Quad, Temp) %>%
  dplyr::summarise(visits = sum(Num)) %>%
  filter(Quad != 'walk') %>%
  mutate(Quad= ifelse( Quad =="Special", "special", Quad)) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  filter(Quad != 2) %>%
  filter(Quad!= 6) %>%
  left_join(quad_visit_meta,., by = c("Tyear", "Start", "Quad", "Temp")) %>%
  mutate(visits = ifelse(is.na(visits), 0, visits)) %>%
  mutate(prop_visits = visits/total_visits) %>%
  filter(!is.na(prop_visits))#proportion of apis visits out of total

##Merge flower abundance and total touches

quad_flower_visit_apis <- merge(quad_flower_sum, quad_visit_sum_apis, by = c("Tyear", "Quad")) %>%
  filter(flower >0) %>%
  mutate(visit_flower_hour = (visits/flower)*3)

##merge infor about burn status

quad_flower_visit_apis <- left_join(quad_flower_visit_apis, transect_meta, by = "Tyear") %>%
  filter(visit_flower_hour < 12)

#individual quads included
p_apis <- ggplot(quad_flower_visit_apis, aes(x = Status, y = visit_flower_hour)) +
  geom_boxplot() +
  facet_wrap(~Year)

p_apis

#individual quads, proportion of apis visits

p_propapis <- ggplot(quad_flower_visit_apis, aes(x = Status, y = prop_visits)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(~Year)

p_propapis

prop_avg_apis <- quad_flower_visit_apis %>%
  group_by(Tyear, Status) %>%
  dplyr::summarise(mean_prop_visits = mean(prop_visits), n=n()) %>%
  merge(.,transect_meta_wtransect, by = "Tyear") %>%
  mutate(Year = as.factor(Year))

p2_propapis <- ggplot(prop_avg_apis, aes(x = Status.y, y = mean_prop_visits)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(~Year)

p2_propapis

prop_apis_visit_model <- lme(mean_prop_visits ~ Status.y*Year, random = ~1|Transect, data = prop_avg_apis)
Anova(prop_apis_visit_model, type = "III")
summary(prop_apis_visit_model)

#Transect averages
quad_flower_visit_avg_apis <- quad_flower_visit_apis %>%
  group_by(Tyear, Status) %>%
  dplyr::summarise(mean_visit_rate = mean(visit_flower_hour), n=n()) %>%
  merge(.,transect_meta, by = "Tyear") %>% 
  filter(mean_visit_rate < 5)

p2_apis <- ggplot(quad_flower_visit_avg_apis, aes(x = Status.y, y = mean_visit_rate)) +
  geom_boxplot() +
  ylim(0,4.5) +
  facet_wrap(~Year)

p2_apis

quad_flower_visit_avg_apis2 <- merge(quad_flower_visit_avg_apis, transect_meta_wtransect, by = "Tyear") %>%
  dplyr::select(Tyear, Transect, Status, mean_visit_rate,n,Year.x) %>%
  mutate(Year.x = as.factor(Year.x))

apis_visit_model <- lme(mean_visit_rate ~ Status*Year.x, random = ~1|Transect, data = quad_flower_visit_avg_apis2)
Anova(apis_visit_model, type = "III")
summary(apis_visit_model)


```



```{r}
##Native visitation rate

quad_visit_sum_native <- visits %>% ##total visits per quad per observation
  filter(Type_pollinator == "BEE") %>%
  filter(Bee_type != "Apis")%>%
  mutate(Tyear = paste(Transect, Year, Round, sep = "_")) %>%
  group_by(Tyear, Start, Quad, Temp) %>%
  dplyr::summarise(visits = sum(Num)) %>%
  filter(Quad != 'walk') %>%
  mutate(Quad= ifelse( Quad =="Special", "special", Quad)) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  filter(Quad != 2) %>%
  filter(Quad!= 6) %>%
  left_join(quad_visit_meta,., by = c("Tyear", "Start", "Quad", "Temp")) %>%
  mutate(visits = ifelse(is.na(visits), 0, visits)) %>%
  mutate(prop_visits = visits/total_visits)%>% #proportion of native visits out of total
  filter(!is.na(prop_visits)) 

##Merge flower abundance and total touches

quad_flower_visit_native <- merge(quad_flower_sum, quad_visit_sum_native, by = c("Tyear", "Quad")) %>%
  filter(flower >0) %>%
  mutate(visit_flower_hour = (visits/flower)*3)

##merge infor about burn status

quad_flower_visit_native <- merge(quad_flower_visit_native, transect_meta, by = "Tyear") 


p_native <- ggplot(quad_flower_visit_native, aes(x = Status, y = visit_flower_hour)) +
  geom_boxplot() +
  facet_wrap(~Year)

p_native

p_propnat <- ggplot(quad_flower_visit_native, aes(x = Status, y = prop_visits)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(~Year)

p_propnat

#transect averages
quad_flower_visit_avg_native <- quad_flower_visit_native %>%
  group_by(Tyear, Status) %>%
  dplyr::summarise(mean_visit_rate = mean(visit_flower_hour), n=n()) %>%
  merge(.,transect_meta, by = "Tyear") %>% 
  filter(mean_visit_rate < 5)

p2_native <- ggplot(quad_flower_visit_avg_native, aes(x = Status.y, y = mean_visit_rate)) +
  geom_boxplot() +
  facet_wrap(~Year)

p2_native

quad_flower_visit_avg_native2 <- merge(quad_flower_visit_avg_native, transect_meta_wtransect, by = "Tyear") %>%
  dplyr::select(Tyear, Transect, Status, mean_visit_rate,n,Year.x) %>%
  mutate(Year.x = as.factor(Year.x))

native_visit_model <- lme(mean_visit_rate ~ Status*Year.x, random = ~1|Transect, data = quad_flower_visit_avg_native2)
Anova(native_visit_model, type = "III")
summary(native_visit_model)

#native proportion visitation

prop_native_visits <- merge(quad_visit_sum, quad_visit_sum_native, by = c("Tyear", "Start"), all = TRUE) %>%
  replace(is.na(.),0) %>%
  mutate(prop_native = visits.y/visits.x*100) %>%
  filter(between(prop_native, 0,100))

prop_native_visits2 <- merge(prop_native_visits, transect_meta_wtransect, by = "Tyear")

p_prop <- ggplot(prop_native_visits2, aes(x = Status, y = prop_native)) +
  geom_boxplot() +
  geom_point()+
  facet_wrap(~Year)

p_prop

quad_flower_visit_avg_prop <- prop_native_visits2 %>%
  group_by(Tyear, Status) %>%
  dplyr::summarise(prop_native = mean(prop_native), n=n()) %>%
  merge(.,transect_meta_wtransect, by = "Tyear") %>%
  mutate(Year = as.factor(Year))

p2_prop <- ggplot(quad_flower_visit_avg_prop, aes(x = Status.x, y = prop_native)) +
  geom_boxplot() +
  geom_point()+
  facet_wrap(~Year)

p2_prop

prop_native_visit_model <- lme(prop_native ~ Status.x*Year, random = ~1|Transect, data = quad_flower_visit_avg_prop)
Anova(prop_native_visit_model, type = "III")
summary(prop_native_visit_model)

```





```{r}

#pollen - find the average pollen grains for each type of flower in each quad, then average across transect #conspecific and heterospecific pollen
# %of counts that have heterospecific pollen on top of conspecific  pollen.count = average all pollen count, het.count = average het count, het.num = ratio of flowers that have heterospecific pollen transfer

pollen_per_quad <- pollen %>%
  mutate(Species = dplyr::recode(Species, "Pha (White)" = "PHACIC", "PHA (White)" = "PHACIC", "BRANG" = "BRANIG", "Purple CALO" = "CALSPL", "Ero" = "EROBOT", "CALO" = "CALCAT", "LUP TRE/SOC" = "LUPTRU", "ERO" = "EROBOT", "LUPTRE" = "LUPTRU", "LUPTRE?" = "LUPTRU", "Mustard" = "HIRINC", "PHARAR" = "PHAPAR", "PHA?" = "PHACIC", "PHA" = "PHACIC", "CALOCHORTUS" = "CALCAT", "TRI" = "TRILAN")) %>%
  filter(!Species %in% c("", "Vak White", "CAMISSONIA", "chaenactis", "UNK Y") ) %>%
  mutate(Tyear = paste(Transect, "2022", Round, sep = "_")) %>%
  group_by(Tyear, Quad, Species)  %>%
  dplyr::summarise(pollen.count = mean(Total.pollen.count), het.count = mean(Heterospecific.pollen.count),
                   het.num = sum(Heterospecific.pollen.count !=0)/sum(Heterospecific.pollen.count)) %>% mutate(het.num = ifelse(is.na(het.num),0,het.num))


pollen_per_transect <- pollen_per_quad %>%
  group_by(Tyear,Species) %>%
  dplyr::summarise(avg.pollen.count = mean(pollen.count), avg.het.count = mean(het.count), avg.het.num = mean(het.num)) %>%
  merge(.,transect_meta_wtransect, by = "Tyear")

salmel_transect_pollen <- pollen_per_transect %>%
  filter(Species %in% c("SALMEL", "HIRINC", "EUCCHR", "EROCIC", "GILANG"))

pollen_transect_gg1 <- ggplot(data = salmel_transect_pollen, aes(y = avg.pollen.count, x = Status)) +
  geom_boxplot()+
  geom_point()+
  facet_wrap(.~Species, scales = "free_y", nrow = 1)

salmel_transect_pollen2 <- salmel_transect_pollen %>%
  filter(Species == "SALMEL")
salmel_pollen_transect_gg <- ggplot(data = salmel_transect_pollen2, aes(y = avg.pollen.count, x = Status)) +
  geom_boxplot()+
  geom_point()+
  facet_wrap(~Species)

#been adjusting the above table to get the different plots
pollen_transect_gg2 <- ggplot(data = salmel_transect_pollen, aes(y = avg.het.num, x = Status)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(.~Species, scales = "free_y", nrow = 1) 

pollen_transect_gg3 <- ggplot(data = salmel_transect_pollen, aes(y = avg.het.count, x = Status)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(.~Species, scales = "free_y", nrow = 1) 

#c("SALMEL", "PHAPAR", "HIRINC", "EUCCHR", "EROCIC", "GILANG"))
aov <- pollen_per_transect %>%
  filter(Species == "SALMEL")

aov_t <- aov(avg.pollen.count ~ Status, data = aov)
summary(aov_t)

aov_hc <- aov(avg.het.count ~ Status, data = aov)
summary(aov_hc)

aov_hn <- aov(avg.het.num ~ Status, data = aov)
summary(aov_hn)


aov_t.tukey <- TukeyHSD(aov_t, 'Status', conf.level = 0.95)
plot(aov_t.tukey)
#pollen transfer vs pollinator activity

```


```{r}
 #CAP of transect visit data and avg pollen end
cap_avg_pollen_long <- pollen_per_transect %>%
  dplyr::select(Tyear, Species, avg.pollen.count)

cap_avg_pollen_wide <- pivot_wider(cap_avg_pollen_long, names_from = Species, values_from = avg.pollen.count) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  data.frame(., row.names = 1) %>%
  as.matrix(.)

transectmeta_2022 <- transect_meta_wtransect %>%
  filter(Year == 2022) %>%
  filter(Tyear %in% row.names(cap_avg_pollen_wide)) %>%
  data.frame(., row.names = 1)

cap_avg_pollen_wide.cap <- capscale(cap_avg_pollen_wide ~ Status, transectmeta_2022, dist = "bray")

avg_pollen_transect.values <- as.data.frame(vegan::scores(cap_avg_pollen_wide.cap, display = "sites"))
avg_pollen_species.values <- as.data.frame(vegan::scores(cap_avg_pollen_wide.cap, display = "sp")) %>%
  mutate_if(.,is.numeric,~.*5) #spread out the labels a bit to see the patterns

transectmeta_2022$CAP1 <- avg_pollen_transect.values$CAP1
transectmeta_2022$CAP2 <- avg_pollen_transect.values$CAP2

pollen_transect.plot <- ggplot(transectmeta_2022, aes(x= CAP1, y= CAP2)) + 
  stat_ellipse(aes(fill = Status), geom = "polygon", alpha = 0.2) +
  geom_point(aes(x=CAP1, y=CAP2, color =  Status)) +
  geom_label(data = avg_pollen_species.values, aes(x= CAP1, y= CAP2, label = row.names(avg_pollen_species.values)), size = 2)  #CAP of transect visit data and avg pollen end
```

```{r}
#How many unique pollinators entered the quadrat during that time

#number of counts visits for fine_pollinator

pollinators_count <- visits %>%
  group_by(Tyear, Quad, Start, fine_pollinator) %>%
  dplyr::mutate(count = n()) %>%
  dplyr::select(Tyear, Quad, Start, Year, fine_pollinator, count) %>%
  distinct()

#number of observations per transect
obs_per_Tyear <- og_visits %>%
  group_by(Tyear) %>%
  dplyr::mutate(quad_count = n_distinct(Start)) %>%
  dplyr::select(Tyear, quad_count) %>%
  distinct()

pollinators_count_Tavg <- pollinators_count %>%
  group_by(Tyear, Year, fine_pollinator) %>%
  summarise_at(vars(count), list(quad_visits = sum))

pollinators_count_Tavg2 <- merge(obs_per_Tyear, pollinators_count_Tavg, by = "Tyear") %>%
  mutate(avgvisits = quad_visits/quad_count*3) %>%
  filter(fine_pollinator != "NA_")#number of visits of different pollinator types per hour for each transect visit

pollinators_count_plot <- ggplot(pollinators_count_Tavg2, aes(x=fine_pollinator, y = avgvisits)) + 
  geom_boxplot() + 
  facet_wrap(~Year) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))

pollinators_count_Tavg3 <- merge(pollinators_count_Tavg2, transect_meta, by = "Tyear")

pollinators_count_plot3 <- ggplot(pollinators_count_Tavg3, aes(x=fine_pollinator, y = avgvisits)) + 
  geom_boxplot() + 
  facet_wrap(~Year.x + Status) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))

```

```{r}

#Relationship between that and flower density separately
#Flower density on x axis, visits/hours on the y axis

quad_visit_sum <- visits %>% ##total visits per quad per observation
  mutate(Tyear = paste(Transect, Year, Round, sep = "_")) %>%
  group_by(Tyear, Start, Quad, Temp) %>%
  dplyr::summarise(visits = sum(Num)) %>%
  filter(Quad != 'walk') %>%
  mutate(Quad= ifelse( Quad =="Special", "special", Quad)) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  filter(Quad != 2) %>%
  filter(Quad!= 6)

##Merge flower abundance and total touches

quad_flower_visit <- merge(quad_flower_sum, quad_visit_sum, by = c("Tyear", "Quad")) %>%
  filter(flower >0) %>%
  mutate(visit_flower_hour = (visits/flower)*3)

#number of visitors on Y, flower abundance on x


#total number of all visits all species and flower abundance

visits_2_abundance <- merge(quad_visit_sum, quad_flower_sum, by = c("Tyear", "Quad"))
visits_2_abundance <- merge(visits_2_abundance, transect_meta_wtransect, by = "Tyear") %>%
  filter(visits<500)
visits_2_abundance_plot <- ggplot(visits_2_abundance, aes(x = flower, y = visits)) +
  geom_point() +
#  scale_x_continuous(trans = log_trans())+
#  scale_y_continuous(trans = log_trans())+
  facet_wrap(~Status) + 
#  stat_summary(fun.data= mean_cl_normal) + 
  geom_smooth(method='lm')


visits_2_abundance_model <- lme(visits ~ flower*Status, random = ~1|Transect, data = visits_2_abundance)
Anova(visits_2_abundance_model, type = "III")
summary(visits_2_abundance_model)




#total apis visitors only and flower abundance
apis_2_abundance <- pollinators_count %>%
  filter(fine_pollinator == "BEE_Apis") %>%
  left_join(quad_flower_sum,., by = c("Tyear", "Quad")) %>%
  filter(!is.na(flower)) %>%
  filter(flower > 0) %>%
  mutate_at(vars(count), ~replace(.,is.na(.),0)) %>%
  filter(!is.na(Start))

apis_2_abundance_transect <- merge(apis_2_abundance,transect_meta_wtransect, by = "Tyear")

apis2_abundance_plot <- ggplot(apis_2_abundance_transect, aes(x=flower, y=count)) +
  geom_point() +
  facet_wrap(~Status)

visits_apis_abundance_model <- lme(count ~ flower*Status, random = ~1|Transect, data = apis_2_abundance_transect)
Anova(visits_apis_abundance_model, type = "III")
summary(visits_apis_abundance_model)


# total other visitors only and flower abundance
other_2_abundance <- pollinators_count %>%
  filter(fine_pollinator != "BEE_Apis") %>%
  filter(fine_pollinator != "NA_") %>%
  group_by(Tyear, Quad, Start) %>%
  summarise_at(vars(count), list(quad_visits = sum))%>%
  left_join(quad_flower_sum,., by = c("Tyear", "Quad")) %>%
  filter(!is.na(flower)) %>%
  filter(flower > 0) %>%
  mutate_at(vars(quad_visits), ~replace(.,is.na(.),0)) %>%
  filter(!is.na(Start))

other_2_abundance_transect <- merge(other_2_abundance,transect_meta_wtransect, by = "Tyear")

other_2_abundance_plot <- ggplot(other_2_abundance_transect, aes(x=flower, y=quad_visits)) +
  geom_point() +
  facet_wrap(~Status)

visits_other_abundance_model <- lme(quad_visits ~ flower*Status, random = ~1|Transect, data = other_2_abundance_transect)
Anova(visits_other_abundance_model, type = "III")
summary(visits_other_abundance_model)

#total number of unique visitors all species and flower abundance

apis_other_visitors <- merge(other_2_abundance_transect,apis_2_abundance_transect, by = c("Tyear","Quad", "Start", "flower", "Status")) %>%
  dplyr::select(Tyear,Quad,Start,flower,Status,Year, quad_visits, count)

colnames(apis_other_visitors) = c("Tyear", "Quad", "Start", "Flower_count", "Status", "Year", "Other", "Apis")

apis_other_visitors <- apis_other_visitors %>% 
  pivot_longer(cols=c("Other", "Apis"),
                    names_to='Visitor',
                    values_to='Visits') 

apis_other_visitor_plot <- ggplot(apis_other_visitors) +
  geom_point(aes(x=Flower_count, y = Visits, colour = Visitor)) +
  facet_wrap(~Status) +
  geom_smooth(method='lm')

apis_other_visitor_plot <- ggplot(apis_other_visitors, aes(x=Flower_count, y = Visits, colour = Visitor)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Status)+
  labs(x = "flower count", y = "number of visitors")

apis_other_visitors.bee <- apis_other_visitors %>%
#  filter(Visitor == 'Apis') %>%
  filter(Visitor == 'Other') %>%
#  filter(Status == "B")
  filter(Status == "M")
#  filter(Status == "U")

rmcorr(Tyear, Flower_count, Visits, apis_other_visitors.bee)

#pivot longer and then geom_smooth()

#do it again but with separate visitations

apis_other_visitations <- visits %>%
  filter(fine_pollinator != "NA_") %>%
  filter(Type_pollinator == "BEE") %>%
  mutate(bee.type = ifelse(fine_pollinator == "BEE_Apis", "Apis", "Native")) %>%
  group_by(Tyear, Quad, Start, bee.type) %>%
  summarise_at(vars(Num), list(visitation = sum)) %>%
  filter(visitation < 500) 
  
apis_other_visitations_flower <- merge(quad_flower_sum, apis_other_visitations, by = c("Tyear", "Quad")) %>%
  left_join(., transect_meta_wtransect, by = "Tyear") %>%
  filter(flower < 4000) %>%
  ggplot(aes(x=flower, y = visitation, colour = bee.type)) +
  geom_point()+
  geom_smooth(method = 'lm') +
  facet_wrap(~Status)

##adding this missing 0s

apis_other_visitations <- visits %>%
  filter(fine_pollinator != "NA_") %>%
  filter(Type_pollinator == "BEE") %>%
  filter(Quad != "walk") %>%
  mutate(bee.type = ifelse(fine_pollinator == "BEE_Apis", "Honeybee", "Nativebee")) %>%
  group_by(Tyear, Quad, Start, bee.type) %>%
  summarise_at(vars(Num), list(visitation = sum)) %>%
  filter(visitation < 500) 
  
apis_other_visitations_flower <- merge(quad_flower_sum, apis_other_visitations, by = c("Tyear", "Quad")) %>%
  left_join(., transect_meta_wtransect, by = "Tyear") 

bee.type <- c("Honeybee", "Nativebee")

apis_other_visitations_flower.bee <- apis_other_visitations_flower%>%
  mutate(bee.type = ifelse(bee.type=="Honeybee", "Honeybee", "Nativebee"))

Tyear_quad_list <- apis_other_visitations_flower.bee %>%
  dplyr::select(Tyear,Quad, flower, Start, Transect, Status, Year) %>%
  distinct()%>%
  crossing(., bee.type) %>%
  left_join(., apis_other_visitations_flower.bee, by = c("Tyear", "Quad","flower","Start","bee.type","Status", "Year", "Transect")) %>%
  mutate_at(vars(visitation), ~replace(.,is.na(.),0))  %>%
  filter(flower < 4000) %>%
  mutate(bee.type = ifelse(bee.type =="Nativebee", "Other", "Apis")) 

apis_other_visitations_flower.plot <-  ggplot(Tyear_quad_list, aes(x=flower, y = visitation, colour = bee.type)) +
  geom_point()+
  geom_smooth(method = 'lm') +
  facet_wrap(~Year+Status)
  #facet_wrap(~Status+Year, scales = "free_x")

#Visitations by themselves, apis
Tyear_quad_list.apis <- Tyear_quad_list %>%
  filter(bee.type == "Apis")

Tyear_quad_list.apis <- Tyear_quad_list.apis %>%
  mutate_at(vars(visitation), as.integer) %>%
  mutate(Year = as.factor(Year)) %>%
  mutate(Status_year = paste(Status, Year, sep = "_"))

apis_visitations_flower.plot <- ggplot(Tyear_quad_list.apis, aes(x = flower, y = visitation, colour = Transect)) +
  geom_point()+
  geom_smooth(method = 'lm', se = FALSE) +
  facet_wrap(~Year +Status, scales = "free_x")

apis_visitations_flower_model <- lme(visitation ~ flower*Status*Year, random = ~1|Transect, data = Tyear_quad_list.apis)
Anova(apis_visitations_flower_model, type = "III")
summary(apis_visitations_flower_model)


apis_visitations_flower_model <- glmmTMB(visitation ~ flower*Status*Year, family = "nbinom1", data = Tyear_quad_list.apis)
summary(apis_visitations_flower_model)
Anova(apis_visitations_flower_model, type = "III")

apis_visitations_flower_model <- glmmTMB(visitation ~ flower + (1|Transect), family = "nbinom1", data = Tyear_quad_list.apis)
summary(apis_visitations_flower_model)

apis_visitations_flower_model <- glmmTMB(visitation ~ flower*Status_year, family = "nbinom1", data = Tyear_quad_list.apis) #for the emtrends

#emtrends(apis_visitations_flower_model, "Status_year", var = "flower")

#apis_visitations_flower_model <- glmer(visitation ~ flower*Status*Year + (1|Transect), data = Tyear_quad_list.apis, family = "poisson")
#Anova(apis_visitations_flower_model, type = "III")
#summary(apis_visitations_flower_model)

#Visitations by themselves, other
Tyear_quad_list.other <- Tyear_quad_list %>%
  filter(bee.type == "Other")

other_visitations_flower.plot <- ggplot(Tyear_quad_list.other, aes(x = flower, y = visitation)) +
  geom_point(colour = "#00BA38")+
  geom_smooth(method = 'lm', colour = "#00BA38") +
  ylim(-10,30) +
  facet_wrap(~Status, scales = "free_x")

other_visitations_flower_model <- lme(visitation ~ flower*Status, random = ~1|Transect, data = Tyear_quad_list.other)
Anova(other_visitations_flower_model, type = "III")
summary(other_visitations_flower_model)


visits_all.bee <- Tyear_quad_list %>%
  filter(bee.type == "Apis") %>%
#  filter(Bee_type == "Other") %>%
  filter(Status == "B")
#  filter(Status == "M")
#  filter(Status == "U")

rmcorr(Tyear, visitation, flower, visits_all.bee)


##summarised averaged for transect

transect_visitations <- Tyear_quad_list %>%
  group_by(Tyear, Status, bee.type) %>%
  summarise_at(vars(flower, visitation), mean) %>%
  filter(visitation < 300) %>%
  mutate(visitations = visitation*3) %>%
  left_join(.,transect_meta_wtransect, by = "Tyear") %>%
#  filter(bee.type == "Apis")
  filter(bee.type == "Other")

transect_visitations.plot <-  ggplot(transect_visitations, aes(x=flower, y = visitations, colour = bee.type)) +
  geom_point(size = 2)+
  geom_smooth(method = 'lm', linewidth = 1) +
  facet_wrap(~Status) +
  xlab("Mean flowers per m2") +
  ylab("Visitations (flower visits per hour)") +
  theme(axis.text = element_text(size = 10), axis.title = element_text(size = 12, face = 'bold'), strip.text.x = element_text(size = 15), legend.text = element_text(size=10), legend.title = element_text(size = 12)) +
  guides(colour = guide_legend(title = "Bee type"))

transect_visitations_flower_model <- lme(visitations ~ flower*Status.x, random = ~1|Transect, data = transect_visitations)
Anova(transect_visitations_flower_model, type = "III")
summary(transect_visitations_flower_model)

#transect_visitations.bee <- transect_visitations %>%
#  mutate(Transect = substring(Tyear, 1, 10))%>%
#  filter(bee.type == "Apis") %>%
#  filter(bee.type == "Other") %>%
#  filter(Status == "B")
#  filter(Status == "M")
#  filter(Status == "U")

#rmcorr(Transect, visitations, flower, transect_visitations.bee)
  

#conspecific pollen ~ burn status and plant species
#missing data if not present in plot

```

```{r}

#separate analysis just for salvia

visits.salvia <- visits %>%
  filter(Veg == "SALMEL") %>%
  left_join(., transect_meta_wtransect, by = "Tyear") %>%
  filter(Type_pollinator == "BEE") %>%
  mutate(Bee_type = ifelse(Bee_type == "Apis", "Apis", "Other")) %>%
  group_by(Tyear, Quad, Start, Bee_type) %>%
  dplyr::summarise(visits = sum(Num)) %>%
  filter(Quad != 'walk') %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  filter(!Quad %in% c(2,6,46,38)) %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_"))

##filtering salvia per quad
quad_flower.salvia <- quad_flower %>%
  filter (Species == "SALMEL") %>%
  dplyr::select(., -c(Total, Average, SPECIAL)) %>%
  mutate_all(~replace(., is.na(.),0)) 

quad_flower.salvia <- quad_flower.salvia %>%
  tidyr::gather(., key = "Quad", value = "count", X0, X5, X10, X15, X20, X25, X30,
                X35, X40, X45) %>%
  mutate(Quad = substring(Quad, 2, nchar(Quad))) %>%
  filter(count >0) %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_"))

#make a list of all the quads where salvia has flowers
#fill <- quad_flower.salvia %>%
#  filter(count >0) %>%
#  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_"))

fill.crossing <- crossing(quad_flower.salvia$Tyear_quad, bee.type) %>%
  dplyr::rename("Tyear_quad" = "quad_flower.salvia$Tyear_quad") %>%
  mutate(Bee_type = ifelse(bee.type=="Honeybee", "Apis", "Other")) 

Tyear_quad.meta <- visits.salvia %>%
  dplyr::select(Tyear_quad, Tyear, Quad)

visits_flower.salvia <- left_join(fill.crossing, visits.salvia, by = c("Tyear_quad", "Bee_type")) %>%
  mutate(visits = ifelse(is.na(visits), 0, visits)) %>%
  left_join(.,quad_flower.salvia, by = "Tyear_quad") %>%
  dplyr::rename("Quad" = "Quad.y") %>%
  dplyr::select(-Quad.x) %>%
  dplyr::rename("Tyear" = "Tyear.y") %>%
  dplyr::select(-Tyear.x) %>%
  mutate(visitations = visits/count) %>%
  left_join(., transect_meta, by = 'Tyear') %>%
  filter(visits <500)

visits.salvia.plot <- ggplot(data = visits_flower.salvia, aes(x = count, y = visits, colour = Bee_type)) +
  geom_point()+
  geom_smooth(method = 'lm') +
  facet_wrap(~Status)

visits_salvia.bee <- visits_flower.salvia %>%
#  filter(Bee_type == "Apis") %>%
  filter(Bee_type == "Other") %>%
  filter(Status == "B")
#  filter(Status == "M")
#  filter(Status == "U")

rmcorr(Tyear, visits, count, visits_salvia.bee)


```

```{r}
#Diversity metrics QUAD QUAD QUAD QUAD QUAD

#Flower diversity metrics for quad
#create meta table with Tyear_quad
Quads <- data.frame(Quads = c("0","5","10","15","20","25","30","35","40","45"))
transectquad_meta <- crossing(transect_meta_wtransect, Quads) %>%
  mutate(Tyear_quad = paste(Tyear, Quads, sep = "_"))

###quad_flower to long and the back to wide so we can get counts for each species in each 

quad_flower.mod <- quad_flower

colnames(quad_flower.mod) <- c("Tyear", "Transect", "Date", "Year", "Round", "Species", "0","5","10","15","20","25","30","35","40","45", "Total", "Average", "SPECIAL")

quad_flower.long <- quad_flower.mod %>% 
  dplyr::select(-c("Total", "Average", "SPECIAL")) %>%
  pivot_longer(cols = c("0","5","10","15","20","25","30","35","40","45"), names_to ='Quad', values_to = "count") %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  mutate(Tyear_quad_species = paste(Tyear_quad, Species, sep = "_")) %>%
  distinct(Tyear_quad_species, .keep_all = TRUE) %>%
  pivot_wider(id_cols = Tyear_quad, names_from = Species, values_from = count) %>%
  dplyr::mutate_all(~replace(., is.na(.), 0)) %>%
  remove_rownames %>%
  column_to_rownames(var = "Tyear_quad") %>%
  mutate(H.div=diversity(.))%>% #create a new data column for the calculation of Shannon's Diversity
  mutate(spec.rich=specnumber(.)) %>% #create a new data column for species richness
  mutate(Even=H.div/log(spec.rich)) %>% #create a new data column for species evenness
  mutate(S.div=diversity(., "inv")) %>% #create a new data column for Simpson's diversity - D2
  dplyr::select(H.div,spec.rich,Even,S.div) %>%
  rownames_to_column("Tyear_quad") %>%
  left_join(transectquad_meta,.,by = "Tyear_quad")

#quad pollinator diversity (unique visitors by category)

 
numeric.Quads <- c(seq(0,45, by = 5))
 
quad_pollinators.mod <- visits %>%
  filter(fine_pollinator_size != "NA__NA") %>%
  filter(Quad %in% numeric.Quads) %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  group_by(Tyear_quad, Start, fine_pollinator_size) %>%
  dplyr::mutate(count = n()) %>%
  dplyr::select(Tyear_quad, Start, fine_pollinator_size, count) %>%
  distinct() %>%
  dplyr::group_by(Tyear_quad, fine_pollinator_size) %>%
  dplyr::summarise(Meancount = (mean(count))) %>%
  ungroup(Tyear_quad, fine_pollinator_size) %>%
  pivot_wider(id_cols = Tyear_quad, names_from = fine_pollinator_size, values_from = Meancount) %>%
  dplyr::mutate_all(~replace(., is.na(.), 0)) %>%
  remove_rownames() %>%
  column_to_rownames(var = "Tyear_quad") %>%
  mutate(H.div=diversity(.))%>% #create a new data column for the calculation of Shannon's Diversity
  mutate(spec.rich=specnumber(.)) %>% #create a new data column for species richness
  mutate(Even=H.div/log(spec.rich)) %>% #create a new data column for species evenness
  mutate(S.div=diversity(., "inv")) %>% #create a new data column for Simpson's diversity - D2
  dplyr::select(H.div,spec.rich,Even,S.div) %>%
  rownames_to_column("Tyear_quad")


#%>%
#  left_join(transectquad_meta,.,by = "Tyear_quad") #need to find all Tyear_quad which had an observation.

visits.simplified <- visits %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  mutate(TYQR_Start = paste(Transect, Year, Quad, Round, Start, sep = "_")) %>%
  filter(Quad %in% numeric.Quads) %>%
  distinct(TYQR_Start, .keep_all = "TRUE") %>% #487 observations
  dplyr::select(Tyear_quad, TYQR_Start) %>% #left_join quad_pollinators.mod to this, add 0s to all NAs, and then run that against the flowering 
  dplyr::left_join(., quad_pollinators.mod, by = 'Tyear_quad') %>%
  dplyr::mutate(spec.rich = ifelse(is.na(spec.rich),0,spec.rich))


flower_visits.div <- left_join(visits.simplified, quad_flower.long, by = "Tyear_quad")

flower_visits.sprich <- ggplot(flower_visits.div, aes(x=spec.rich.y, y = spec.rich.x)) +
  geom_point() +
  facet_wrap(~Year+Status)

flower_visits.hdiv <- ggplot(flower_visits.div, aes(x=H.div.y, y = H.div.x)) +
  geom_point() +
  facet_wrap(~Year + Status) +
  xlab("Flower diversity") +
  ylab("Pollinator diversity") +
  geom_smooth(method='lm')

#relationship of diversity of pollinators against diversity of flowers
 #for the emtrends

flower_visits_div_model1 <- lme(H.div.x ~ H.div.y*Status, random = ~1|Transect, data = (flower_visits.div %>% filter(!is.na(H.div.x))))
Anova(flower_visits_div_model1, type = "III")

flower_visits.div <- flower_visits.div %>%
  mutate(Status_year = paste(Status, Year, sep = "_"))
flower_visits_div_model2 <- lme(H.div.x ~ H.div.y*Status_year, random = ~1|Transect, data = (flower_visits.div %>% filter(!is.na(H.div.x))))

emtrends(flower_visits_div_model2, "Status_year", var = "H.div.y")

```

```{r}
#Diversity metrics TRANSECT TRANSECT TRANSECT
test.qfs <- quad_flower_sum %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  left_join(., flower_visits.div, by = "Tyear_quad") %>%
  dplyr::select(Tyear_quad, flower, spec.rich.x, spec.rich.y) %>%
  filter(!is.na(spec.rich.x)) %>%
  arrange(flower)
```

```{r}
all.type.visitations <- visits %>%
  filter(fine_pollinator != "NA_") %>%
  mutate(bee.type = ifelse(!fine_pollinator %in% c("BEE_Apis", "BEE_Native"),"Other", fine_pollinator)) %>%
  group_by(Tyear, Quad, Start, bee.type) %>%
  summarise_at(vars(Num), list(visitation = sum)) %>%
  filter(visitation < 500) 

all.type.visitations.flower <- merge(quad_flower_sum, all.type.visitations, by = c("Tyear", "Quad")) %>%
  left_join(., transect_meta_wtransect, by = "Tyear") %>%
  filter(flower < 4000) 

all.type.visitations.flower.plot<-ggplot(all.type.visitations.flower, aes(x=flower, y = visitation, colour = bee.type)) +
  geom_point()+
  geom_smooth(method = 'lm') +
  facet_wrap(~Status)

#with zeros added in

bee.type <- c("BEE_Apis", "BEE_Native", "Other")

all.type.visitations.flower.withzero <- all.type.visitations.flower %>%
  dplyr::select(Tyear,Quad, flower, Start, Transect, Status, Year) %>%
  distinct()%>%
  crossing(., bee.type) %>%
  left_join(., all.type.visitations.flower, by = c("Tyear", "Quad","flower","Start","bee.type","Status", "Year", "Transect")) %>%
  mutate_at(vars(visitation), ~replace(.,is.na(.),0))  %>%
  filter(flower < 4000) %>%
  mutate(bee.type = ifelse(bee.type == "BEE_Native", "BEE_Other", bee.type)) %>%
  mutate(visitation = as.integer(visitation)) %>%
  mutate(Year = as.factor(Year))


all.type.visitations.flower.withzero.plot<-ggplot(all.type.visitations.flower.withzero, aes(x=flower, y = visitation, colour = bee.type)) +
  geom_point()+
  geom_smooth(method = 'lm') +
  facet_wrap(~Year+Status)

apis.visitations.flower.withzero <- all.type.visitations.flower.withzero %>%
  filter(bee.type == "BEE_Apis") %>%
  mutate(Status_year = paste(Status, Year, sep = "_")) #%>%
  #ggplot(., aes(x = flower, y = visitation)) +
  #geom_point()+
  #geom_smooth(method = 'lm') +
  #facet_wrap(~Year+Status)

apis.visitations.flower.withzero.model <- glmmTMB(visitation~flower*Status*Year, family = "nbinom1", data = apis.visitations.flower.withzero)
summary(apis.visitations.flower.withzero.model)
Anova(apis.visitations.flower.withzero.model, type = "III")

nonapis.visitations.flower.withzero <- all.type.visitations.flower.withzero %>%
  filter(bee.type == "BEE_Other") %>%
  mutate(Status_year = paste(Status, Year, sep = "_"))
nonapis.visitations.flower.withzero.model <- glmmTMB(visitation~flower*Status*Year, family = "nbinom1", data = nonapis.visitations.flower.withzero)
summary(nonapis.visitations.flower.withzero.model)
Anova(nonapis.visitations.flower.withzero.model, type = "III")

other.visitations.flower.withzero <- all.type.visitations.flower.withzero %>%
  filter(bee.type == "Other") %>%
  mutate(Status_year = paste(Status, Year, sep = "_"))
other.visitations.flower.withzero.model <- glmmTMB(visitation~flower*Status*Year, family = "nbinom1", data = other.visitations.flower.withzero)
summary(other.visitations.flower.withzero.model)
Anova(other.visitations.flower.withzero.model, type = "III")


#trendlines for each
apis.visitations.flower.withzero.model <- glmmTMB(visitation~flower*Status_year, family = "nbinom1", data = apis.visitations.flower.withzero)
emtrends(apis.visitations.flower.withzero.model, "Status_year", var = "flower")

nonapis.visitations.flower.withzero.model <- glmmTMB(visitation~flower*Status_year, family = "nbinom1", data = nonapis.visitations.flower.withzero)
emtrends(nonapis.visitations.flower.withzero.model, "Status_year", var = "flower")

other.visitations.flower.withzero.model <- glmmTMB(visitation~flower*Status_year, family = "nbinom1", data = other.visitations.flower.withzero)
emtrends(other.visitations.flower.withzero.model, "Status_year", var = "flower")


```




```{r}
#total apis visitors only and flower abundance
apis_2_abundance <- pollinators_count %>%
  filter(fine_pollinator == "BEE_Apis") %>%
  left_join(quad_flower_sum,., by = c("Tyear", "Quad")) %>%
  filter(!is.na(flower)) %>%
  filter(flower > 0) %>%
  mutate_at(vars(count), ~replace(.,is.na(.),0)) %>%
  filter(!is.na(Start))

apis_2_abundance_transect <- merge(apis_2_abundance,transect_meta_wtransect, by = c("Tyear", "Year"))%>%
  dplyr::rename("apis.count" = "count") 

# total other bee visitors only and flower abundance
otherbee_2_abundance <- pollinators_count %>%
  filter(fine_pollinator %in% c("BEE_Native", "BEE_Bombus")) %>%
  group_by(Tyear, Quad, Start) %>%
  summarise_at(vars(count), list(quad_visits = sum))%>%
  left_join(quad_flower_sum,., by = c("Tyear", "Quad")) %>%
  filter(!is.na(flower)) %>%
  filter(flower > 0) %>%
  mutate_at(vars(quad_visits), ~replace(.,is.na(.),0)) %>%
  filter(!is.na(Start))

otherbee_2_abundance_transect <- merge(otherbee_2_abundance,transect_meta_wtransect, by = "Tyear")%>%
  dplyr::rename("otherbee.count" = "quad_visits")

# total other visitors only and flower abundance
other_2_abundance <- pollinators_count %>%
  filter(fine_pollinator != "NA_") %>%
  filter(!fine_pollinator %in% c("BEE_Apis", "BEE_Native", "BEE_Bombus")) %>%
  group_by(Tyear, Quad, Start) %>%
  summarise_at(vars(count), list(quad_visits = sum))%>%
  left_join(quad_flower_sum,., by = c("Tyear", "Quad")) %>%
  filter(!is.na(flower)) %>%
  filter(flower > 0) %>%
  mutate_at(vars(quad_visits), ~replace(.,is.na(.),0)) %>%
  filter(!is.na(Start))

other_2_abundance_transect <- merge(other_2_abundance,transect_meta_wtransect, by = "Tyear") %>%
  dplyr::rename("other.count" = "quad_visits")

#total number of unique visitors all species and flower abundance
#####HERE
apis_other_visitors <- merge(other_2_abundance_transect,apis_2_abundance_transect, by = c("Tyear","Quad", "Start", "flower", "Status", "Year", "Transect"), all = T) %>%
  merge(.,otherbee_2_abundance_transect, by = c("Tyear","Quad", "Start", "flower", "Status", "Year", "Transect"), all = T) %>% 
  mutate_at(c("other.count","otherbee.count","apis.count"), ~replace_na(.,0))

apis_other_visitors <- apis_other_visitors %>% 
  pivot_longer(cols=c("apis.count", "otherbee.count", "other.count"),
                    names_to='Visitor.identity',
                    values_to='Unique.visitors') 

apis_other_visitor_plot <- ggplot(apis_other_visitors, aes(x=flower, y = Unique.visitors, colour = Visitor.identity)) +
  geom_point() +
  facet_wrap(~Year+Status) +
  geom_smooth(method='lm')

#all unique visitors in each quad

all.unique.visitors <- apis_other_visitors %>%
  group_by(Tyear, Quad, Start, Status, Year, Transect) %>%
  summarise_at(vars(Unique.visitors, flower), list(Unique.visitors = sum, flower = sum)) %>%
  dplyr::rename(flower = flower_flower, Unique.visitors = Unique.visitors_Unique.visitors) %>%
  mutate(Year = as.factor(Year)) %>%
  dplyr::select(-flower_Unique.visitors, -Unique.visitors_flower)

all.unique.visitors.model <- glmmTMB(Unique.visitors~flower*Status*Year + (1|Transect), family = "nbinom1", data = all.unique.visitors)
summary(all.unique.visitors.model)
Anova(all.unique.visitors.model, type = "III")
  
all.unique.visitors.plot <- ggplot(all.unique.visitors, aes(x = Status, y = Unique.visitors)) +
  geom_violin()+
  geom_point()+
  facet_wrap(~Year)

emtrends(flower_visits_div_model2, "Status_year", var = "H.div.y")

avg.quad.visits.model <- glmmTMB(visits~ Status.x*Year.x, family = "nbinom1", data = avg.quad.visits) #transect random removed because it was throwing close to 0 variances
summary(avg.quad.visits.model)
Anova(avg.quad.visits.model, type = "III")


```

```{r}
 #CAP of transect visit data and avg pollen end QUAD QUAD QUAD

pollinator.cat.abundance <- pollinators_count %>%
  filter(fine_pollinator != "NA_") %>%
  left_join(transect_meta_wtransect,., by = "Tyear") %>%
  filter(!is.na(count)) %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  dplyr::select(Tyear_quad, fine_pollinator, count) %>%
  rowid_to_column()%>%
  pivot_wider(., names_from = fine_pollinator, values_from = count) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  group_by(Tyear_quad) %>%
  dplyr::summarise(across(BEE_Bombus:SAW, sum)) %>% 
  data.frame(., row.names = 1) %>%
  dplyr::rename("BEE_Other" = "BEE_Native", "BOM" = "LID", "LEP" = "FLY") %>%
  as.matrix(.)

transectmeta.pollinator <- pollinators_count %>%
  filter(fine_pollinator != "NA_") %>%
  left_join(transect_meta_wtransect,., by = c("Tyear", "Year")) %>%
  filter(!is.na(count)) %>%
  mutate(Tyear_quad = paste(Tyear, Quad, sep = "_")) %>%
  distinct(Tyear_quad, .keep_all = T) %>%
  dplyr::select(Tyear_quad, Tyear, Transect, Status, Year) %>%
  data.frame(., row.names = "Tyear_quad")

pollinator.cat.cap <- capscale(pollinator.cat.abundance ~ Status, transectmeta.pollinator, dist = "bray")

pollinator.cat.quad <- as.data.frame(vegan::scores(pollinator.cat.cap, display = "sites"))
pollinator.cat.sp <- as.data.frame(vegan::scores(pollinator.cat.cap, display = "sp")) %>%
  mutate_if(.,is.numeric,~.*5) #spread out the labels a bit to see the patterns

transectmeta.pollinator$CAP1 <- pollinator.cat.quad$CAP1
transectmeta.pollinator$CAP2 <- pollinator.cat.quad$CAP2

pollinator.cat.plot <- pollen_transect.plot <- ggplot(transectmeta.pollinator, aes(x= CAP1, y= CAP2)) + 
  stat_ellipse(aes(fill = Status), geom = "polygon", alpha = 0.2) +
  geom_point(aes(x=CAP1, y=CAP2, color =  Status)) +
  geom_label(data = pollinator.cat.sp, aes(x= CAP1, y= CAP2, label = row.names(pollinator.cat.sp)), size = 2)

```


```{r}
 #CAP of transect visit data and avg pollen end TRANSECT MEAN TRANSECT MEAN TRANSECT MEAN

pollinator.cat.abundance <- pollinators_count %>%
  filter(fine_pollinator != "NA_") %>%
  left_join(transect_meta_wtransect,., by = "Tyear") %>%
  filter(!is.na(count)) %>%
  dplyr::select(Tyear, fine_pollinator, count) %>%
  rowid_to_column()%>%
  pivot_wider(., names_from = fine_pollinator, values_from = count) %>%
  mutate_all(~replace(., is.na(.),0)) %>%
  group_by(Tyear) %>%
  dplyr::summarise(across(BEE_Bombus:SAW, mean)) %>% 
  data.frame(., row.names = 1) %>%
  dplyr::rename("BEE_Other" = "BEE_Native", "BOM" = "LID", "LEP" = "FLY") %>%
  as.matrix(.)

transectmeta.pollinator <- pollinators_count %>%
  filter(fine_pollinator != "NA_") %>%
  left_join(transect_meta_wtransect,., by = c("Tyear", "Year")) %>%
  filter(!is.na(count)) %>%
  distinct(Tyear, .keep_all = T) %>%
  dplyr::select(Tyear, Transect, Status, Year) %>%
  data.frame(., row.names = "Tyear")

pollinator.cat.cap <- capscale(pollinator.cat.abundance ~ Status, transectmeta.pollinator, dist = "bray")

pollinator.cat.quad <- as.data.frame(vegan::scores(pollinator.cat.cap, display = "sites"))
pollinator.cat.sp <- as.data.frame(vegan::scores(pollinator.cat.cap, display = "sp")) %>%
  mutate_if(.,is.numeric,~.*5) #spread out the labels a bit to see the patterns

transectmeta.pollinator$CAP1 <- pollinator.cat.quad$CAP1
transectmeta.pollinator$CAP2 <- pollinator.cat.quad$CAP2

pollinator.cat.plot <- pollen_transect.plot <- ggplot(transectmeta.pollinator, aes(x= CAP1, y= CAP2)) + 
  stat_ellipse(aes(fill = Status), geom = "polygon", alpha = 0.2) +
  geom_point(aes(x=CAP1, y=CAP2, color =  Status)) +
  geom_label(data = pollinator.cat.sp, aes(x= CAP1, y= CAP2, label = row.names(pollinator.cat.sp)), size = 2)

anova.cca(pollinator.cat.cap, by = "term")

```


